### ISSUE TITLE
Licensing change

### ISSUE THREAD

**Issue by Caopi** [Klortho/d3-flextree#18]
Is it possible to change the license of this software to an OSI approved license like the "Unlicense"? https://choosealicense.com/licenses/unlicense/ https://unlicense.org/

The current WTFPL license is very vague does not include mentions regarding liability, warranty and public domain and isn't court tested, which is why my company is hesitant to actually use code licensed under it and it could also potentially be problematic for you as author. The Unlicense has all of the same freedoms that you seem to want from the WTFPL, but fixes the problems I mentioned above.

**Comment by Klortho** [comment]
I think you completely miss the point of the WTFPL.
Not gonna happen.

**Comment by Venryx** [comment]
@Caopi If your company is hesitant to use the software because of the WTFPL license, you can literally just make a copy of the library, and relicense it under whatever you want.

See this section from the official WTFPL FAQ: http://www.wtfpl.net/faq
> **Can’t you change the wording? It’s inappropriate / childish / not corporate-compliant.**
> The WTFPL lets you relicense the work under any other license.

(you can read the rest of the FAQ for further clarity/confirmation on this)

I'm certainly a fan of this freedom! For example, it is why I am now using this library, rather than the GPL-licensed alternative here: https://github.com/codeledge/entitree-flex

The `entitree-flex` library has a few more features, but [its using the GPL license](https://github.com/codeledge/entitree-flex/issues/7) is absolutely a no-go for my project, as the GPL places constraints that I don't want for my project (which is fully open-source, but _not copyleft_), and so far I have managed to keep it free from infective licenses like that.

**Comment by m-gallesio** [comment]
@Klortho The license currently in this repository still mentions Sam Hocevar (the author of the WTFPL) as the author, though. I think at least that should be changed.
